---
abstract: 'DBIx::Class without the class.'
author:
  - 'Brad Haywood <brad@geeksware.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Inline
no_index:
  directory:
    - inc
    - t
version: 0.03
